args <- commandArgs(trailingOnly = TRUE)
mode <- if (length(args)) args[1] else "all"

# Final paper timing convention:
# - E1 uses R/e1_mcch_vs_global.R.
# - E2 uses timing-v3 (R/e2_timing_v3.R + R/summarize_e2_timing_v3.R).
# - R/e2_end_to_end.R and R/helpers_timing.R are retained only for the small
#   smoke/validation workflow in run_smoke.R and are not the source of the
#   E2 timing values reported in the paper.

run_e1_final <- function() {
  source(file.path("R", "e1_mcch_vs_global.R"))
  run_e1(FALSE)
}

run_e2_gaussian_final <- function() {
  source(file.path("R", "e2_timing_v3.R"))
  run_e2_gaussian_timing_v3()
}

run_e2_discrete_final <- function() {
  source(file.path("R", "e2_timing_v3.R"))
  run_e2_discrete_timing_v3()
}

summarize_final <- function() {
  source(file.path("R", "summarize_e1_e2.R"))
  if (file.exists(file.path(DIR_E1, "e1_raw.csv"))) summarize_e1(FALSE)

  source(file.path("R", "summarize_e2_timing_v3.R"))
  summarize_e2_timing_v3()
}

make_figures_final <- function() {
  source(file.path("R", "figures_e1_e2.R"))
  if (file.exists(file.path(DIR_E1, "e1_summary.csv"))) plot_e1()
  message("E2 timing-v3 tables are generated by summarize_e2_timing_v3.R. ",
          "The manuscript-level combined E2 figure is distributed with the ",
          "paper/figure sources rather than regenerated by the legacy figure helper.")
}

if (mode == "e1") {
  run_e1_final()
} else if (mode == "e2-gaussian") {
  run_e2_gaussian_final()
} else if (mode == "e2-discrete") {
  run_e2_discrete_final()
} else if (mode == "summary") {
  summarize_final()
} else if (mode == "figures") {
  make_figures_final()
} else if (mode == "smoke") {
  source("run_smoke.R")
} else if (mode == "all") {
  run_e1_final()
  run_e2_gaussian_final()
  run_e2_discrete_final()
  summarize_final()
} else {
  stop(paste(
    "Usage: Rscript run_all.R",
    "[e1|e2-gaussian|e2-discrete|summary|figures|smoke|all]"
  ))
}
